"""Initial schema

Revision ID: a4d54c52ab53
Revises: 
Create Date: 2026-07-08 14:53:49.805783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d54c52ab53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('circuit_breakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breakers_id'), 'circuit_breakers', ['id'], unique=False)
    op.create_index(op.f('ix_circuit_breakers_service_id'), 'circuit_breakers', ['service_id'], unique=False)
    op.create_index(op.f('ix_circuit_breakers_state'), 'circuit_breakers', ['state'], unique=False)
    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_snapshots_id'), 'health_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_service_id'), 'health_snapshots', ['service_id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_status'), 'health_snapshots', ['status'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_logs_service_id'), 'request_logs', ['service_id'], unique=False)
    op.create_index(op.f('ix_request_logs_status_code'), 'request_logs', ['status_code'], unique=False)
    op.create_table('retry_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_attempts_id'), 'retry_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_retry_attempts_request_id'), 'retry_attempts', ['request_id'], unique=False)
    op.create_index(op.f('ix_retry_attempts_service_id'), 'retry_attempts', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_attempts_service_id'), table_name='retry_attempts')
    op.drop_index(op.f('ix_retry_attempts_request_id'), table_name='retry_attempts')
    op.drop_index(op.f('ix_retry_attempts_id'), table_name='retry_attempts')
    op.drop_table('retry_attempts')
    op.drop_index(op.f('ix_request_logs_status_code'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_service_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_health_snapshots_status'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_service_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_id'), table_name='health_snapshots')
    op.drop_table('health_snapshots')
    op.drop_index(op.f('ix_circuit_breakers_state'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_service_id'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_id'), table_name='circuit_breakers')
    op.drop_table('circuit_breakers')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
